name: Release

on:
  push:
    tags:
      - "*"

jobs:
  call-build-workflow:
    if: startsWith(github.ref, 'refs/tags')
    uses: jeffborg/evcc/.github/workflows/default.yml@master

  docker:
    name: Publish Docker :release
    needs:
      - call-build-workflow
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/jeffborg/evcc

      - name: Publish
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          push: true
          build-args: |
            RELEASE=1
          tags: ${{ steps.meta.outputs.tags }}
