name: Sync taggs Finalize Tagging

on:
  pull_request:
    types:
      - closed
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  finalize:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches and tags
          token: ${{ secrets.EVCC_PAT }}

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get merged branch name
        id: get-branch
        run: echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Validate branch name
        id: validate-branch
        run: |
          # Extract the tag name from the branch name
          TAG_NAME=$(echo "${{ env.BRANCH }}" | sed 's/tag-//')

          # Check if the tag name matches the expected pattern
          if [[ ! "$TAG_NAME" =~ ^0\.[0-9]+\.[0-9]+$ ]]; then
            echo "Branch name does not match the expected pattern. Skipping tag creation."
            exit 1
          else
            echo "Valid branch name: $TAG_NAME Saving for next step"
            echo "BRANCH=$TAG_NAME" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Tag the merged branch
        if: success() && steps.validate-branch.outcome == 'success'
        run: |
          # Checkout the branch that was merged
          git checkout "${{ env.BRANCH }}"

          # Create the new tag
          NEW_TAG="${{ steps.validate-branch.outputs.BRANCH }}.0"

          # Tag the branch
          git tag "${NEW_TAG}"

          # Push the tag to the repository
          git push origin "${NEW_TAG}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
